services:
  student-rest-api:
    platform: linux/x86_64
    build: .
    tty: true
    stdin_open: true
    restart: unless-stopped
    container_name: student-rest-api
    ports:
      - 8000:8000
    depends_on:
      - redis


  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - 6379:6379

